services:
  main-app:
    env_file:
      - ./.env
    build:
      dockerfile: Dockerfile
    ports:
      - "${APP_PORT}:${APP_DOCKER_PORT}"
    volumes:
      - type: bind
        source: ./models
        target: /flats_app/models
    hostname: flats_app

  prometheus:
    image: prom/prometheus
    command:
      - '--config.file=/prometheus/prometheus.yml'
    ports:
      - ${PROMETHEUS_PORT}:${PROMETHEUS_PORT}
    volumes:
      - "./prometheus/prometheus.yml:/prometheus/prometheus.yml"
    hostname: prometheus

  grafana:
        image: grafana/grafana
        env_file:
        - ./.env
        ports:
        - ${GRAFANA_PORT}:${GRAFANA_PORT}
        environment:
        - GF_SECURITY_ADMIN_USER=${GRAFANA_USER}
        - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASS}